(cl:in-package dual_arm_control-srv)
(cl:export '(SLIDE_R-VAL
          SLIDE_R
          JOINT1_R-VAL
          JOINT1_R
          JOINT2_R-VAL
          JOINT2_R
          JOINT3_R-VAL
          JOINT3_R
          JOINT4_R-VAL
          JOINT4_R
          JOINT5_R-VAL
          JOINT5_R
          JOINT6_R-VAL
          JOINT6_R
          JOINT7_R-VAL
          JOINT7_R
          GRIPPER_R-VAL
          GRIPPER_R
          SLIDE_L-VAL
          SLIDE_L
          JOINT1_L-VAL
          JOINT1_L
          JOINT2_L-VAL
          JOINT2_L
          JOINT3_L-VAL
          JOINT3_L
          JOINT4_L-VAL
          JOINT4_L
          JOINT5_L-VAL
          JOINT5_L
          JOINT6_L-VAL
          JOINT6_L
          JOINT7_L-VAL
          JOINT7_L
          GRIPPER_L-VAL
          GRIPPER_L
          STATE-VAL
          STATE
))