{crossTime: 0.5, errorAng: 1, errorCorrectionDis: 60, errorMoibleAng: 3, errorMoibledis: 1000,
  errorRotate0: 5, errorRotate90: 92, maxVel: 10.0, minVel: 20, rotateSlowAng: 20,
  rotateYaw: 45, velYaw: 20}
