{crossTime: 0.6, errorAng: 1, errorCorrectionDis: 60, errorMoibleAng: 2, errorMoibledis: 1000,
  errorRotate0: 3, errorRotate90: 90, maxVel: 10.0, minVel: 20, rotateSlowAng: 20,
  rotateYaw: 45, velYaw: 16}
