// Generated by gencpp from file dual_arm_control/robot.msg
// DO NOT EDIT!


#ifndef DUAL_ARM_CONTROL_MESSAGE_ROBOT_H
#define DUAL_ARM_CONTROL_MESSAGE_ROBOT_H

#include <ros/service_traits.h>


#include <dual_arm_control/robotRequest.h>
#include <dual_arm_control/robotResponse.h>


namespace dual_arm_control
{

struct robot
{

typedef robotRequest Request;
typedef robotResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct robot
} // namespace dual_arm_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dual_arm_control::robot > {
  static const char* value()
  {
    return "302798b026bfb5b41c3f90f1e942eb92";
  }

  static const char* value(const ::dual_arm_control::robot&) { return value(); }
};

template<>
struct DataType< ::dual_arm_control::robot > {
  static const char* value()
  {
    return "dual_arm_control/robot";
  }

  static const char* value(const ::dual_arm_control::robot&) { return value(); }
};


// service_traits::MD5Sum< ::dual_arm_control::robotRequest> should match 
// service_traits::MD5Sum< ::dual_arm_control::robot > 
template<>
struct MD5Sum< ::dual_arm_control::robotRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dual_arm_control::robot >::value();
  }
  static const char* value(const ::dual_arm_control::robotRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dual_arm_control::robotRequest> should match 
// service_traits::DataType< ::dual_arm_control::robot > 
template<>
struct DataType< ::dual_arm_control::robotRequest>
{
  static const char* value()
  {
    return DataType< ::dual_arm_control::robot >::value();
  }
  static const char* value(const ::dual_arm_control::robotRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dual_arm_control::robotResponse> should match 
// service_traits::MD5Sum< ::dual_arm_control::robot > 
template<>
struct MD5Sum< ::dual_arm_control::robotResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dual_arm_control::robot >::value();
  }
  static const char* value(const ::dual_arm_control::robotResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dual_arm_control::robotResponse> should match 
// service_traits::DataType< ::dual_arm_control::robot > 
template<>
struct DataType< ::dual_arm_control::robotResponse>
{
  static const char* value()
  {
    return DataType< ::dual_arm_control::robot >::value();
  }
  static const char* value(const ::dual_arm_control::robotResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DUAL_ARM_CONTROL_MESSAGE_ROBOT_H
