// Generated by gencpp from file dual_arm_control/robot_msg.msg
// DO NOT EDIT!


#ifndef DUAL_ARM_CONTROL_MESSAGE_ROBOT_MSG_H
#define DUAL_ARM_CONTROL_MESSAGE_ROBOT_MSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dual_arm_control
{
template <class ContainerAllocator>
struct robot_msg_
{
  typedef robot_msg_<ContainerAllocator> Type;

  robot_msg_()
    : A(0.0)  {
    }
  robot_msg_(const ContainerAllocator& _alloc)
    : A(0.0)  {
  (void)_alloc;
    }



   typedef float _A_type;
  _A_type A;





  typedef boost::shared_ptr< ::dual_arm_control::robot_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dual_arm_control::robot_msg_<ContainerAllocator> const> ConstPtr;

}; // struct robot_msg_

typedef ::dual_arm_control::robot_msg_<std::allocator<void> > robot_msg;

typedef boost::shared_ptr< ::dual_arm_control::robot_msg > robot_msgPtr;
typedef boost::shared_ptr< ::dual_arm_control::robot_msg const> robot_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dual_arm_control::robot_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dual_arm_control::robot_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace dual_arm_control

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'dual_arm_control': ['/home/wrs/wrs2018/wrs_ws/src/wrs_gazebo/dual_arm_control/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::dual_arm_control::robot_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dual_arm_control::robot_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dual_arm_control::robot_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dual_arm_control::robot_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dual_arm_control::robot_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dual_arm_control::robot_msg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dual_arm_control::robot_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "86dc5e57feab1a2b50e6db6b5a647d08";
  }

  static const char* value(const ::dual_arm_control::robot_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x86dc5e57feab1a2bULL;
  static const uint64_t static_value2 = 0x50e6db6b5a647d08ULL;
};

template<class ContainerAllocator>
struct DataType< ::dual_arm_control::robot_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dual_arm_control/robot_msg";
  }

  static const char* value(const ::dual_arm_control::robot_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dual_arm_control::robot_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 A\n\
";
  }

  static const char* value(const ::dual_arm_control::robot_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dual_arm_control::robot_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.A);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct robot_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dual_arm_control::robot_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dual_arm_control::robot_msg_<ContainerAllocator>& v)
  {
    s << indent << "A: ";
    Printer<float>::stream(s, indent + "  ", v.A);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DUAL_ARM_CONTROL_MESSAGE_ROBOT_MSG_H
