// Generated by gencpp from file dual_arm_control/robotResponse.msg
// DO NOT EDIT!


#ifndef DUAL_ARM_CONTROL_MESSAGE_ROBOTRESPONSE_H
#define DUAL_ARM_CONTROL_MESSAGE_ROBOTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dual_arm_control
{
template <class ContainerAllocator>
struct robotResponse_
{
  typedef robotResponse_<ContainerAllocator> Type;

  robotResponse_()
    : state()  {
    }
  robotResponse_(const ContainerAllocator& _alloc)
    : state(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _state_type;
  _state_type state;





  typedef boost::shared_ptr< ::dual_arm_control::robotResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dual_arm_control::robotResponse_<ContainerAllocator> const> ConstPtr;

}; // struct robotResponse_

typedef ::dual_arm_control::robotResponse_<std::allocator<void> > robotResponse;

typedef boost::shared_ptr< ::dual_arm_control::robotResponse > robotResponsePtr;
typedef boost::shared_ptr< ::dual_arm_control::robotResponse const> robotResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dual_arm_control::robotResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dual_arm_control::robotResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace dual_arm_control

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'dual_arm_control': ['/home/wrs/wrs2018/wrs_ws/src/wrs_gazebo/dual_arm_control/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::dual_arm_control::robotResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dual_arm_control::robotResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dual_arm_control::robotResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dual_arm_control::robotResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dual_arm_control::robotResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dual_arm_control::robotResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dual_arm_control::robotResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "af6d3a99f0fbeb66d3248fa4b3e675fb";
  }

  static const char* value(const ::dual_arm_control::robotResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xaf6d3a99f0fbeb66ULL;
  static const uint64_t static_value2 = 0xd3248fa4b3e675fbULL;
};

template<class ContainerAllocator>
struct DataType< ::dual_arm_control::robotResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dual_arm_control/robotResponse";
  }

  static const char* value(const ::dual_arm_control::robotResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dual_arm_control::robotResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string state\n\
\n\
";
  }

  static const char* value(const ::dual_arm_control::robotResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dual_arm_control::robotResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct robotResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dual_arm_control::robotResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dual_arm_control::robotResponse_<ContainerAllocator>& v)
  {
    s << indent << "state: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DUAL_ARM_CONTROL_MESSAGE_ROBOTRESPONSE_H
