// Generated by gencpp from file manipulator_h_base_module_msgs/GetJointPose.msg
// DO NOT EDIT!


#ifndef MANIPULATOR_H_BASE_MODULE_MSGS_MESSAGE_GETJOINTPOSE_H
#define MANIPULATOR_H_BASE_MODULE_MSGS_MESSAGE_GETJOINTPOSE_H

#include <ros/service_traits.h>


#include <manipulator_h_base_module_msgs/GetJointPoseRequest.h>
#include <manipulator_h_base_module_msgs/GetJointPoseResponse.h>


namespace manipulator_h_base_module_msgs
{

struct GetJointPose
{

typedef GetJointPoseRequest Request;
typedef GetJointPoseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetJointPose
} // namespace manipulator_h_base_module_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::manipulator_h_base_module_msgs::GetJointPose > {
  static const char* value()
  {
    return "a41e2236bf819259792cbf06540699bd";
  }

  static const char* value(const ::manipulator_h_base_module_msgs::GetJointPose&) { return value(); }
};

template<>
struct DataType< ::manipulator_h_base_module_msgs::GetJointPose > {
  static const char* value()
  {
    return "manipulator_h_base_module_msgs/GetJointPose";
  }

  static const char* value(const ::manipulator_h_base_module_msgs::GetJointPose&) { return value(); }
};


// service_traits::MD5Sum< ::manipulator_h_base_module_msgs::GetJointPoseRequest> should match 
// service_traits::MD5Sum< ::manipulator_h_base_module_msgs::GetJointPose > 
template<>
struct MD5Sum< ::manipulator_h_base_module_msgs::GetJointPoseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::manipulator_h_base_module_msgs::GetJointPose >::value();
  }
  static const char* value(const ::manipulator_h_base_module_msgs::GetJointPoseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::manipulator_h_base_module_msgs::GetJointPoseRequest> should match 
// service_traits::DataType< ::manipulator_h_base_module_msgs::GetJointPose > 
template<>
struct DataType< ::manipulator_h_base_module_msgs::GetJointPoseRequest>
{
  static const char* value()
  {
    return DataType< ::manipulator_h_base_module_msgs::GetJointPose >::value();
  }
  static const char* value(const ::manipulator_h_base_module_msgs::GetJointPoseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::manipulator_h_base_module_msgs::GetJointPoseResponse> should match 
// service_traits::MD5Sum< ::manipulator_h_base_module_msgs::GetJointPose > 
template<>
struct MD5Sum< ::manipulator_h_base_module_msgs::GetJointPoseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::manipulator_h_base_module_msgs::GetJointPose >::value();
  }
  static const char* value(const ::manipulator_h_base_module_msgs::GetJointPoseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::manipulator_h_base_module_msgs::GetJointPoseResponse> should match 
// service_traits::DataType< ::manipulator_h_base_module_msgs::GetJointPose > 
template<>
struct DataType< ::manipulator_h_base_module_msgs::GetJointPoseResponse>
{
  static const char* value()
  {
    return DataType< ::manipulator_h_base_module_msgs::GetJointPose >::value();
  }
  static const char* value(const ::manipulator_h_base_module_msgs::GetJointPoseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MANIPULATOR_H_BASE_MODULE_MSGS_MESSAGE_GETJOINTPOSE_H
