// Generated by gencpp from file manipulator_h_base_module_msgs/GetKinematicsPoseResponse.msg
// DO NOT EDIT!


#ifndef MANIPULATOR_H_BASE_MODULE_MSGS_MESSAGE_GETKINEMATICSPOSERESPONSE_H
#define MANIPULATOR_H_BASE_MODULE_MSGS_MESSAGE_GETKINEMATICSPOSERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace manipulator_h_base_module_msgs
{
template <class ContainerAllocator>
struct GetKinematicsPoseResponse_
{
  typedef GetKinematicsPoseResponse_<ContainerAllocator> Type;

  GetKinematicsPoseResponse_()
    : group_pose()
    , phi(0.0)  {
    }
  GetKinematicsPoseResponse_(const ContainerAllocator& _alloc)
    : group_pose(_alloc)
    , phi(0.0)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _group_pose_type;
  _group_pose_type group_pose;

   typedef double _phi_type;
  _phi_type phi;





  typedef boost::shared_ptr< ::manipulator_h_base_module_msgs::GetKinematicsPoseResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::manipulator_h_base_module_msgs::GetKinematicsPoseResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetKinematicsPoseResponse_

typedef ::manipulator_h_base_module_msgs::GetKinematicsPoseResponse_<std::allocator<void> > GetKinematicsPoseResponse;

typedef boost::shared_ptr< ::manipulator_h_base_module_msgs::GetKinematicsPoseResponse > GetKinematicsPoseResponsePtr;
typedef boost::shared_ptr< ::manipulator_h_base_module_msgs::GetKinematicsPoseResponse const> GetKinematicsPoseResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::manipulator_h_base_module_msgs::GetKinematicsPoseResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::manipulator_h_base_module_msgs::GetKinematicsPoseResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace manipulator_h_base_module_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'manipulator_h_base_module_msgs': ['/home/andy/wrs_ws/src/ROBOTIS/ROBOTIS-MANIPULATOR-H/manipulator_h_base_module_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::manipulator_h_base_module_msgs::GetKinematicsPoseResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::manipulator_h_base_module_msgs::GetKinematicsPoseResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::manipulator_h_base_module_msgs::GetKinematicsPoseResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::manipulator_h_base_module_msgs::GetKinematicsPoseResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::manipulator_h_base_module_msgs::GetKinematicsPoseResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::manipulator_h_base_module_msgs::GetKinematicsPoseResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::manipulator_h_base_module_msgs::GetKinematicsPoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6263acace284e74dd391246b8f61717d";
  }

  static const char* value(const ::manipulator_h_base_module_msgs::GetKinematicsPoseResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6263acace284e74dULL;
  static const uint64_t static_value2 = 0xd391246b8f61717dULL;
};

template<class ContainerAllocator>
struct DataType< ::manipulator_h_base_module_msgs::GetKinematicsPoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "manipulator_h_base_module_msgs/GetKinematicsPoseResponse";
  }

  static const char* value(const ::manipulator_h_base_module_msgs::GetKinematicsPoseResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::manipulator_h_base_module_msgs::GetKinematicsPoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Pose group_pose\n\
float64        phi\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of position and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
";
  }

  static const char* value(const ::manipulator_h_base_module_msgs::GetKinematicsPoseResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::manipulator_h_base_module_msgs::GetKinematicsPoseResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.group_pose);
      stream.next(m.phi);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetKinematicsPoseResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::manipulator_h_base_module_msgs::GetKinematicsPoseResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::manipulator_h_base_module_msgs::GetKinematicsPoseResponse_<ContainerAllocator>& v)
  {
    s << indent << "group_pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.group_pose);
    s << indent << "phi: ";
    Printer<double>::stream(s, indent + "  ", v.phi);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MANIPULATOR_H_BASE_MODULE_MSGS_MESSAGE_GETKINEMATICSPOSERESPONSE_H
